// Imports
import { BaseFolder, TextFile } from "./files";

// Defines root
export const root = new BaseFolder("root", null);
root.add(new TextFile("hai.txt", root, "haiii"));
root.add(new TextFile("yooo.txt", root, "yooooo"));
root.add(new TextFile("gopew.txt", root, "go pew?"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));
root.add(new TextFile("??.txt", root, "never gonna give you up"));

// Exports
export default root;